## TODO: Make this into a full blown integration test

## health-check
GET http://localhost:4000/health-check
Content-Type: application/json
Accept: application/json

## query
GET http://localhost:4000/query?query-string=frege
Content-Type: application/json
Accept: application/json

## login
POST http://localhost:4000/login
Content-Type: application/json
Accept: application/json
Authorization: Basic YW5wYXJpc2k6b25l

## user
POST https://localhost:4000/admin/user/add
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFucGFyaXNpIiwicm9sZSI6ImFkbWluIiwic3ViIjoiYW5wYXJpc2kiLCJqdGkiOiJiZmYwYzcxYy1lYjIxLTRhMGYtYjNiNy0yZGFkYzk3MGQ1ODIiLCJpYXQiOjE3MzgyMTM4NTAsImV4cCI6MTczODIxNTY1MH0.b6pwwx7Ye8C06XaP9lPZXxRNPorz3eYMm97ff5Xr7ak

{
  "email": "george",
  "password": "george",
  "role": "user"
}
